export const EM_FROMSERVER_DATA: string = 'EM/FROMSERVER/DATA';
export const EM_FROMCLIENT_SETPROFILE: string = 'EM/FROMCLIENT/SETPROFILE';
export const EM_FROMCLIENT_SETSTATUS: string = 'EM/FROMCLIENT/SETSTATUS';
export const EM_FROMCLIENT_GETPROFILES: string = 'EM/FROMCLIENT/GETPROFILES';
export const EM_FROMSERVER_PROFILES: string = 'EM/FROMSERVER/PROFILES';
